spring:
  application:
    name: lovable-clone

  datasource:
    url: jdbc:postgresql://localhost:9000/testDB?options=-c%20TimeZone=Asia/Kolkata
    username: testUser
    password: Hardwell18@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
jwt:
  secret-key: "asfasa86fas9fa2fsgj5d6j7f3d6h8k4"
