spring:
  application:
    name: lovable-clone

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: test
    password: Hardwell18@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
